// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/weather.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeatherData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datetime  string  `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Tempmin   float32 `protobuf:"fixed32,2,opt,name=tempmin,proto3" json:"tempmin,omitempty"`
	Tempmax   float32 `protobuf:"fixed32,3,opt,name=tempmax,proto3" json:"tempmax,omitempty"`
	Humidity  float32 `protobuf:"fixed32,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Precip    float32 `protobuf:"fixed32,5,opt,name=precip,proto3" json:"precip,omitempty"`
	Snow      float32 `protobuf:"fixed32,6,opt,name=snow,proto3" json:"snow,omitempty"`
	Snowdepth float32 `protobuf:"fixed32,7,opt,name=snowdepth,proto3" json:"snowdepth,omitempty"`
	Windspeed float32 `protobuf:"fixed32,8,opt,name=windspeed,proto3" json:"windspeed,omitempty"`
	Temp      float32 `protobuf:"fixed32,9,opt,name=temp,proto3" json:"temp,omitempty"`
}

func (x *WeatherData) Reset() {
	*x = WeatherData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherData) ProtoMessage() {}

func (x *WeatherData) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherData.ProtoReflect.Descriptor instead.
func (*WeatherData) Descriptor() ([]byte, []int) {
	return file_api_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherData) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *WeatherData) GetTempmin() float32 {
	if x != nil {
		return x.Tempmin
	}
	return 0
}

func (x *WeatherData) GetTempmax() float32 {
	if x != nil {
		return x.Tempmax
	}
	return 0
}

func (x *WeatherData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *WeatherData) GetPrecip() float32 {
	if x != nil {
		return x.Precip
	}
	return 0
}

func (x *WeatherData) GetSnow() float32 {
	if x != nil {
		return x.Snow
	}
	return 0
}

func (x *WeatherData) GetSnowdepth() float32 {
	if x != nil {
		return x.Snowdepth
	}
	return 0
}

func (x *WeatherData) GetWindspeed() float32 {
	if x != nil {
		return x.Windspeed
	}
	return 0
}

func (x *WeatherData) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

type Weather struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day    *WeatherData   `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Hourly []*WeatherData `protobuf:"bytes,2,rep,name=hourly,proto3" json:"hourly,omitempty"`
}

func (x *Weather) Reset() {
	*x = Weather{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_api_weather_proto_rawDescGZIP(), []int{1}
}

func (x *Weather) GetDay() *WeatherData {
	if x != nil {
		return x.Day
	}
	return nil
}

func (x *Weather) GetHourly() []*WeatherData {
	if x != nil {
		return x.Hourly
	}
	return nil
}

type WeatherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Datetime string `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
}

func (x *WeatherRequest) Reset() {
	*x = WeatherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_weather_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherRequest) ProtoMessage() {}

func (x *WeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weather_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherRequest.ProtoReflect.Descriptor instead.
func (*WeatherRequest) Descriptor() ([]byte, []int) {
	return file_api_weather_proto_rawDescGZIP(), []int{2}
}

func (x *WeatherRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *WeatherRequest) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

var File_api_weather_proto protoreflect.FileDescriptor

var file_api_weather_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0xf5, 0x01, 0x0a, 0x0b, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65,
	0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x6d, 0x70, 0x6d, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x74, 0x65, 0x6d, 0x70, 0x6d, 0x69, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x65, 0x6d, 0x70, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x74, 0x65, 0x6d, 0x70, 0x6d, 0x61, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x70, 0x72, 0x65, 0x63, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6e, 0x6f, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x6e, 0x6f, 0x77,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6e, 0x6f, 0x77, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x73, 0x6e, 0x6f, 0x77, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x77, 0x69, 0x6e, 0x64, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x6d, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x74, 0x65, 0x6d, 0x70,
	0x22, 0x57, 0x0a, 0x07, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12,
	0x28, 0x0a, 0x06, 0x68, 0x6f, 0x75, 0x72, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x06, 0x68, 0x6f, 0x75, 0x72, 0x6c, 0x79, 0x22, 0x48, 0x0a, 0x0e, 0x57, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x32, 0x41, 0x0a, 0x0e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x65, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x57,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x61, 0x7a, 0x61, 0x72, 0x62, 0x65, 0x79, 0x65, 0x6e,
	0x65, 0x61, 0x7a, 0x75, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_weather_proto_rawDescOnce sync.Once
	file_api_weather_proto_rawDescData = file_api_weather_proto_rawDesc
)

func file_api_weather_proto_rawDescGZIP() []byte {
	file_api_weather_proto_rawDescOnce.Do(func() {
		file_api_weather_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_weather_proto_rawDescData)
	})
	return file_api_weather_proto_rawDescData
}

var file_api_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_weather_proto_goTypes = []interface{}{
	(*WeatherData)(nil),    // 0: api.WeatherData
	(*Weather)(nil),        // 1: api.Weather
	(*WeatherRequest)(nil), // 2: api.WeatherRequest
}
var file_api_weather_proto_depIdxs = []int32{
	0, // 0: api.Weather.day:type_name -> api.WeatherData
	0, // 1: api.Weather.hourly:type_name -> api.WeatherData
	2, // 2: api.WeatherService.GetWeather:input_type -> api.WeatherRequest
	1, // 3: api.WeatherService.GetWeather:output_type -> api.Weather
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_weather_proto_init() }
func file_api_weather_proto_init() {
	if File_api_weather_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_weather_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weather); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_weather_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeatherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_weather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weather_proto_goTypes,
		DependencyIndexes: file_api_weather_proto_depIdxs,
		MessageInfos:      file_api_weather_proto_msgTypes,
	}.Build()
	File_api_weather_proto = out.File
	file_api_weather_proto_rawDesc = nil
	file_api_weather_proto_goTypes = nil
	file_api_weather_proto_depIdxs = nil
}
