debug: true
database:
  url: mongodb://db:27017
grpcAddr: 0.0.0.0:2000
visualcrossing: 
  base_url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/%s/%s?key=MAF6M4LQ43NCG7GH995NN57BV
